# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e66248fae858c83e45cd1542103c28ca491af19366084bab78d93a09b0807344ac6f58a9986afdb8a44d5536039b713c4278f781c9124196751f53a791ce251

test:
  secret_key_base: bd71d2f808973c7463766eee994343cde7eb62ab8cef0d67041aac104aaebbd4a83d3e80080dc9638e508c671aac4465cf7744b8411223020310ffb853b43806

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
